[build-system]
requires = ["scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "mpc_cpp_extension"
version = "0.0.1"
description = "High-performance C++ MPC solver for Robot Soccer"
requires-python = ">=3.11"